title: Yejin's Devtfolio
profile_img: /assets/custom/profile-1.png
icon_img: /assets/custom/favicon.ico

name: "안녕하세요!<br/>신입 개발자 안예진입니다."
job: ""

# phone_number: 012-345-6789
# address: 
email: yj.osoq@gmail.com
# linkedin_username: linkedin
github_username: yj59
# instagram_username: instagram
# twitter_username: twitter
# facebook_username: facebook
# youtube_username: youtube
blog_url: https://yj59.github.io/

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag